CREATE TABLE [dbo].[Galaxy]
(
  [Id] INT NOT NULL IDENTITY,
  [Name] NVARCHAR(50) NOT NULL,
  [Description] NVARCHAR(2000) NULL,
  
  CONSTRAINT [PK_Galaxy] PRIMARY KEY([Id]),
  CONSTRAINT [UK_Galaxy] UNIQUE([Name])
)
